// Generated by gencpp from file armbot_move/SavePositionRequest.msg
// DO NOT EDIT!


#ifndef ARMBOT_MOVE_MESSAGE_SAVEPOSITIONREQUEST_H
#define ARMBOT_MOVE_MESSAGE_SAVEPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armbot_move
{
template <class ContainerAllocator>
struct SavePositionRequest_
{
  typedef SavePositionRequest_<ContainerAllocator> Type;

  SavePositionRequest_()
    : save()  {
    }
  SavePositionRequest_(const ContainerAllocator& _alloc)
    : save(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _save_type;
  _save_type save;





  typedef boost::shared_ptr< ::armbot_move::SavePositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armbot_move::SavePositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SavePositionRequest_

typedef ::armbot_move::SavePositionRequest_<std::allocator<void> > SavePositionRequest;

typedef boost::shared_ptr< ::armbot_move::SavePositionRequest > SavePositionRequestPtr;
typedef boost::shared_ptr< ::armbot_move::SavePositionRequest const> SavePositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armbot_move::SavePositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armbot_move::SavePositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::armbot_move::SavePositionRequest_<ContainerAllocator1> & lhs, const ::armbot_move::SavePositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.save == rhs.save;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::armbot_move::SavePositionRequest_<ContainerAllocator1> & lhs, const ::armbot_move::SavePositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace armbot_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armbot_move::SavePositionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armbot_move::SavePositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armbot_move::SavePositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e104100265146051383c5a794b30ab04";
  }

  static const char* value(const ::armbot_move::SavePositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe104100265146051ULL;
  static const uint64_t static_value2 = 0x383c5a794b30ab04ULL;
};

template<class ContainerAllocator>
struct DataType< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armbot_move/SavePositionRequest";
  }

  static const char* value(const ::armbot_move::SavePositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string save\n"
;
  }

  static const char* value(const ::armbot_move::SavePositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.save);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SavePositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armbot_move::SavePositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armbot_move::SavePositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "save: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.save);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMBOT_MOVE_MESSAGE_SAVEPOSITIONREQUEST_H
