// Generated by gencpp from file armbot_move/SavePosition.msg
// DO NOT EDIT!


#ifndef ARMBOT_MOVE_MESSAGE_SAVEPOSITION_H
#define ARMBOT_MOVE_MESSAGE_SAVEPOSITION_H

#include <ros/service_traits.h>


#include <armbot_move/SavePositionRequest.h>
#include <armbot_move/SavePositionResponse.h>


namespace armbot_move
{

struct SavePosition
{

typedef SavePositionRequest Request;
typedef SavePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SavePosition
} // namespace armbot_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armbot_move::SavePosition > {
  static const char* value()
  {
    return "61b51a87ebe23475b436f7b122d27fe9";
  }

  static const char* value(const ::armbot_move::SavePosition&) { return value(); }
};

template<>
struct DataType< ::armbot_move::SavePosition > {
  static const char* value()
  {
    return "armbot_move/SavePosition";
  }

  static const char* value(const ::armbot_move::SavePosition&) { return value(); }
};


// service_traits::MD5Sum< ::armbot_move::SavePositionRequest> should match
// service_traits::MD5Sum< ::armbot_move::SavePosition >
template<>
struct MD5Sum< ::armbot_move::SavePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armbot_move::SavePosition >::value();
  }
  static const char* value(const ::armbot_move::SavePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armbot_move::SavePositionRequest> should match
// service_traits::DataType< ::armbot_move::SavePosition >
template<>
struct DataType< ::armbot_move::SavePositionRequest>
{
  static const char* value()
  {
    return DataType< ::armbot_move::SavePosition >::value();
  }
  static const char* value(const ::armbot_move::SavePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armbot_move::SavePositionResponse> should match
// service_traits::MD5Sum< ::armbot_move::SavePosition >
template<>
struct MD5Sum< ::armbot_move::SavePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armbot_move::SavePosition >::value();
  }
  static const char* value(const ::armbot_move::SavePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armbot_move::SavePositionResponse> should match
// service_traits::DataType< ::armbot_move::SavePosition >
template<>
struct DataType< ::armbot_move::SavePositionResponse>
{
  static const char* value()
  {
    return DataType< ::armbot_move::SavePosition >::value();
  }
  static const char* value(const ::armbot_move::SavePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMBOT_MOVE_MESSAGE_SAVEPOSITION_H
