controller_list:
  - name: fake_arm_group_controller
    type: $(arg execution_type)
    joints:
      - base_to_motors
      - link2_horizontal_bottom_link3_vertical
      - link3_vertical_to_link4_horizontal_top_long
initial:  # Define initial robot poses.
  - group: arm_group
    pose: initial_pose