controller_list:
  - name: fake_robot_arm_controller
    type: $(arg execution_type)
    joints:
      - base_to_motors
      - motors_to_link1_vertical
      - motors_to_link2_horizontal_bottom
      - link2_horizontal_bottom_to_link3_vertical
      - link3_vertical_to_link4_horizontal_top_long
      - motors_to_link5_vertical
      - link5_vertical_to_triangle
      - triangle_to_link7_horizontal_top_short
      - link7_horizontal_top_short_tool
  - name: fake_robot_hand_controller
    type: $(arg execution_type)
    joints:
      - link7_horizontal_top_short_tool
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: start_pose