set(_CATKIN_CURRENT_PACKAGE "armbot_move")
set(armbot_move_VERSION "0.0.0")
set(armbot_move_MAINTAINER "e <e@todo.todo>")
set(armbot_move_PACKAGE_FORMAT "2")
set(armbot_move_BUILD_DEPENDS "roscpp" "std_msgs" "sensor_msgs" "urdf" "message_generation")
set(armbot_move_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "urdf")
set(armbot_move_BUILDTOOL_DEPENDS "catkin")
set(armbot_move_BUILDTOOL_EXPORT_DEPENDS )
set(armbot_move_EXEC_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "urdf" "message_runtime" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher")
set(armbot_move_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "urdf" "message_runtime" "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher")
set(armbot_move_TEST_DEPENDS )
set(armbot_move_DOC_DEPENDS )
set(armbot_move_URL_WEBSITE "")
set(armbot_move_URL_BUGTRACKER "")
set(armbot_move_URL_REPOSITORY "")
set(armbot_move_DEPRECATED "")