set(_CATKIN_CURRENT_PACKAGE "armbot_description")
set(armbot_description_VERSION "0.0.0")
set(armbot_description_MAINTAINER "Luke <liuzhufu@dobot.cc>")
set(armbot_description_PACKAGE_FORMAT "1")
set(armbot_description_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs")
set(armbot_description_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "geometry_msgs")
set(armbot_description_BUILDTOOL_DEPENDS "catkin")
set(armbot_description_BUILDTOOL_EXPORT_DEPENDS )
set(armbot_description_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "geometry_msgs")
set(armbot_description_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime" "geometry_msgs")
set(armbot_description_TEST_DEPENDS )
set(armbot_description_DOC_DEPENDS )
set(armbot_description_URL_WEBSITE "")
set(armbot_description_URL_BUGTRACKER "")
set(armbot_description_URL_REPOSITORY "")
set(armbot_description_DEPRECATED "")