armbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  gazebo_ros_control:
    pid_gains:
      joint_1:
        p: 100.0
        i: 0.0
        d: 0.0
      joint_2:
        p: 100.0
        i: 0.0
        d: 0.0
      joint_3:
        p: 100.0
        i: 0.0
        d: 0.0
      joint_4:
        p: 100.0
        i: 0.0
        d: 0.0
      joint_grip:
        p: 100.0
        i: 0.0
        d: 0.0
  
  # Position Controllers ---------------------------------------
  arm_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_grip
    gains:
      joint_1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_end:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_grip:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
  controller_list:
    - name: armbot/arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_grip



#    type: position_controllers/JointPositionController
#    joint: joint_1
#    pid: {p: 1000.0, i: 0.0, d: 0.0}
#  joint_2_position_controller:
#    type: position_controllers/JointPositionController
#    joint: joint_2
#    pid: {p: 500.0, i: 0.0, d: 0.0}
#  joint_3_position_controller:
#    type: position_controllers/JointPositionController
#    joint: joint_3
#    pid: {p: 300.0, i: 0.0, d: 0.0}
#  joint_4_position_controller:
#    type: position_controllers/JointPositionController
#    joint: joint_4
#    pid: {p: 100.0, i: 0.0, d: 0.0}
#  joint_grip_position_controller:
#    type: position_controllers/JointPositionController
#    joint: joint_grip
#    pid: {p: 0.0, i: 0.0, d: 0.0}
