armbot:
  gazebo_ros_control:   
    type: position_controllers/JointPositionController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_end
      - joint_grip
    pid_gains:
      joint_1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      joint_end:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
