armbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  gazebo_ros_control:
    pid_gains:
      joint_1:
        p: 100
        d: 0
        i: 0
        i_clamp: 100
      joint_2:
        p: 100
        d: 0
        i: 0
        i_clamp: 100
      joint_3:
        p: 100
        d: 0
        i: 0
        i_clamp: 100
      joint_4:
        p: 100
        d: 0
        i: 0
        i_clamp: 1
      joint_end:
        p: 100
        d: 0
        i: 0
        i_clamp: 100
      joint_grip:
        p: 100
        d: 0
        i: 0
        i_clamp: 100
  
  # Position Controllers ---------------------------------------
  arm_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_grip
  controller_list:
    - name: armbot/arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_grip