armbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  gazebo_ros_control:
    pid_gains:
      joint_1:
        p: 1000
        d: 0
        i: 0
        i_clamp: 100
      joint_2:
        p: 1000
        d: 0
        i: 0
        i_clamp: 100
      joint_3:
        p: 1000
        d: 0
        i: 0
        i_clamp: 100
      joint_4:
        p: 1000
        d: 0
        i: 0
        i_clamp: 1
      joint_end:
        p: 1000
        d: 0
        i: 0
        i_clamp: 1000
      joint_grip:
        p: 50
        d: 0
        i: 0
        i_clamp: 100
  
  arm_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_grip
    gains:
      joint_1: { p: 1000, i: 0, d: 0, i_clamp: 100}
      joint_2: { p: 1000, i: 0, d: 0, i_clamp: 100}
      joint_3: { p: 1000, i: 0, d: 0, i_clamp: 100}
      joint_4: { p: 1000, i: 0, d: 0, i_clamp: 100}
      joint_grip: { p: 1000, i: 0, d: 0, i_clamp: 100}

controller_list:
  - name: armbot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_grip
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_grip
  sim_control_mode: 1  # 0: position, 1: velocity

moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: arm_start

generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01