(cl:defpackage armbot_move-srv
  (:use )
  (:export
   "SAVEPOSITION"
   "<SAVEPOSITION-REQUEST>"
   "SAVEPOSITION-REQUEST"
   "<SAVEPOSITION-RESPONSE>"
   "SAVEPOSITION-RESPONSE"
   "SETPOSITION"
   "<SETPOSITION-REQUEST>"
   "SETPOSITION-REQUEST"
   "<SETPOSITION-RESPONSE>"
   "SETPOSITION-RESPONSE"
  ))

