controller_list:
  - name: fake_magician_arm_controller
    joints:
      - magician_joint1
      - magician_joint2
      - magician_joint3
  - name: fake_magician_eff_group_controller
    joints:
      []
  - name: fake_manipulator_controller
    joints:
      - magician_joint1
      - magician_joint2
      - magician_joint3
initial:  # Define initial robot poses.
  - group: magician_arm
    pose: home
  - group: manipulator
    pose: home